[workspace]
authors = ["Igors Dubanevics <26872977+igorsdub@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "typer-tutorial"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
typer = ">=0.21.1,<0.22"
